
version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  adminer:
    image: adminer:4.8.1
    restart: always
    ports: 
      - 8080:8080
volumes:
  postgres_data: